/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.equipothee.helloworld;

public final class R {
  public static final class id {
    public static final int btnRemoveSent=0x7f010000;
    public static final int btnResetPrefix=0x7f010001;
    public static final int btnResetSearch=0x7f010002;
    public static final int btnResetUrl=0x7f010003;
    public static final int btnSelectionAuto=0x7f010004;
    public static final int btnSelectionManuelle=0x7f010005;
    public static final int btnSend=0x7f010006;
    public static final int btnVider=0x7f010007;
    public static final int logView=0x7f010008;
    public static final int prefixField=0x7f010009;
    public static final int scrollView=0x7f01000a;
    public static final int searchField=0x7f01000b;
    public static final int urlField=0x7f01000c;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
}